### ISSUE TITLE
Live query block is too huge

### ISSUE THREAD

**Issue by optimistic5** [Bad3r/Logseq-Nord-Theme#2]
Live query block looks huge.
This is default theme
![image](https://user-images.githubusercontent.com/25054050/230891625-06b23d88-f87a-40da-9d18-06a629c4e1c2.png)

This is Logseq-Nord-Theme
![image](https://user-images.githubusercontent.com/25054050/230891754-32287522-5715-4438-ab7d-13166cbf26cb.png)

[This](https://discord.com/channels/725182569297215569/1093889772096860201/1094637969291354152) block of code is reduce size of `Live query` block
```css
.custom-query > div:first-child {
    box-shadow: none;
    background-color: var(--ls-primary-background-color);
    border-radius: 0;
    padding: 0.25rem;
    margin: 0;
    position: relative;
}
```
![image](https://user-images.githubusercontent.com/25054050/230892375-04d7c146-e2ba-4e82-b183-303ec93b3df5.png)
