### ISSUE TITLE
Broken CSS of Calculator

### ISSUE THREAD

**Issue by optimistic5** [Bad3r/Logseq-Nord-Theme#4]
CSS of `/Calculator` block looks broken 
![image](https://user-images.githubusercontent.com/25054050/235461999-18e3c2bc-73d8-4b6b-a912-1e132e3f7b0b.png)

```markdown
3+3+3
1+1+1+1111111
```

My `custom.css`
```css
@import url("https://cdn.jsdelivr.net/gh/bad3r/logseq-nord-theme@latest/custom.min.css");

.recent {
    display: none;
  }
```

Logseq 0.9.4
