### ISSUE TITLE
Top and bottom on mobile Logseq looks different

### ISSUE THREAD

**Issue by optimistic5** [Bad3r/Logseq-Nord-Theme#5]
Sorry, I'm not sure is it theme issue or Logseq issue itself.

The system top an bottom panel has another color scheme on mobile 
![image](https://user-images.githubusercontent.com/25054050/236320312-016d555d-f24f-4020-b492-3243bece577a.png)

Logseq 0.9.4
Android 12
Samsung A41.

My `custom.css`
```css
@import url("https://cdn.jsdelivr.net/gh/bad3r/logseq-nord-theme@latest/custom.min.css");

.recent {
    display: none;
  }
  ```
